title: "Kriteen Shrestha's Personal Website"
author: "Kriteen Shrestha"
description: "A piece of Kriteen's brain"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", title: "Home", sidebaricon: home} # intro to website
  - {file: "README.md", title: "About me", sidebaricon: address-card} # quick bio, resume, etc.
  - {file: "braindumps.md", title: "Research", sidebaricon: brain} # paper + exploration blog post 


external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Github, icon: github, url: "https://github.com/kriteenshrestha"}
  - {title: LinkedIn, icon: rss, url: "https://www.linkedin.com/in/kriteen-shrestha/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
